name: i18n

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Check i18n keys
        run: yarn workspace desktop-client check-i18n --fail-on-update
